# 서버 포트 설정
server:
  port: 8085

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://copytixe.iptime.org:3306/mydatabase
    #url: jdbc:mysql://localhost:3306/carry_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: myuser
    #username: rot
    password: 112358

  thymeleaf:
    cache: false
  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            security:
              servlet:
                SecurityAutoConfiguration:

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

